[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "9a6494d9c634016f09c1ba99bc5ecb81a30fe2ef"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "ad5e805178c0510f00289c103307da7c3cc01ec382ca58d09e6b07fe9a93ed6a"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-2+0/Dynare_preprocessor.v4.7.0-2.x86_64-apple-darwin14.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "917d88e62bb267b760847f3ea1bb483b75815680"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "d9163bb87acc9c56cf6cccd6374bc982ad6bb6b03674ce780f775237c765c926"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-2+0/Dynare_preprocessor.v4.7.0-2.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "6b9910ab460b5af9ac27d077407be60aefb86216"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "3d5de3ff08cbbf2a415a95d5c73e8e463659388d37a393ee9babe0f009233185"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-2+0/Dynare_preprocessor.v4.7.0-2.x86_64-w64-mingw32.tar.gz"
