[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "c5100e920153eee03b4c808d326b8ffdd6a637c5"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "ca4a2a89afb5cd6c525e6e5bf50fd89aeeb2f54a68ab07f656892de55aaf5e86"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-3+3/Dynare_preprocessor.v4.8.0-3.x86_64-apple-darwin.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "4de123aebd9f3e0f7f1e2914b60e023d0c1fcd09"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "57d3025e9129036be729dd20cbe28020a146152035cc9411fb8ee6826cfd3f2e"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-3+3/Dynare_preprocessor.v4.8.0-3.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "d5d4cd19aa288db487da27e5f05651f14ef2c74f"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "655b0579c4c6b7b690d3da0139bfbfa72d4adeb48d779c8784b5b68318a1e91d"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-3+3/Dynare_preprocessor.v4.8.0-3.x86_64-w64-mingw32.tar.gz"
