[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "90a7dd0b9143c432ab4ad181b71040c9b743b0f4"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "67e280d4256b172c124238bf55a20d4b946207065b27d2efffc6233d42aae956"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-2+2/Dynare_preprocessor.v4.8.0-2.x86_64-apple-darwin.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "d352d64c79543eaaa34d5dceae2edbf1c412c411"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "78fe621a262c30c8e7a85354dcd604921b06a1d322f305aeec45eefdf27f7278"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-2+2/Dynare_preprocessor.v4.8.0-2.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "60280e8803687e64666eba7e82719c4636ef3647"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "cb46f409dd18bf895477ed94404c90e493d102ebe1234027cf829186cb2ddb75"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-2+2/Dynare_preprocessor.v4.8.0-2.x86_64-w64-mingw32.tar.gz"
