[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "5b9c754f4e893638f6e8aacfa53f891402daeea9"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "50196876262be4905cc10cef9bf13c53ef1f23f565bd1c2fb2b8880a447820b0"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0+0/Dynare_preprocessor.v4.7.0.x86_64-apple-darwin14.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "ff9566390fde455279f190b6177f0b2637582368"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "4084b024f0867ceb06325e9c4ca842e1220c1b770dde876b493fa81c61c050e7"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0+0/Dynare_preprocessor.v4.7.0.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "6bbf34c4abec3c4881abb73feab444f0e977e70d"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "b7363db4999eb9d27add07f5518a9ca9d16a06f71fdfa7b74896383d746097c7"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0+0/Dynare_preprocessor.v4.7.0.x86_64-w64-mingw32.tar.gz"
