[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "314e97e75ac416721a2b872c4267021e79f038a5"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "1fa1a196d5ee36c5f7572b2a011987a18ee8f049b145eb19280ff506b75a3115"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-3+0/Dynare_preprocessor.v4.7.0-3.x86_64-apple-darwin14.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "b4a8c6c1bc041a8febc871fce21af0196b51913a"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "f9ae18ef8cf87ae0648bf53ef8428dc8d6d05d23b4f33673a9a997d0a84ab043"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-3+0/Dynare_preprocessor.v4.7.0-3.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "315c8dd12f52a70590d31c8b764568e2458362f8"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "477981abb6740f772977d2795c42d7dba4215debfe1d604bc334c48dc6b9324c"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.7.0-3+0/Dynare_preprocessor.v4.7.0-3.x86_64-w64-mingw32.tar.gz"
