[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "20c6bfcb95491aba02a7b3471f4feb1788d984eb"
os = "macos"

    [[Dynare_preprocessor.download]]
    sha256 = "3f9e7976d676c47ef332a6995d21feb0dad824425c266a5928e1b87aa094d291"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-1+0/Dynare_preprocessor.v4.8.0-1.x86_64-apple-darwin.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "43687c9c3277fd9bd4f41e0112658cd2527b581b"
libc = "glibc"
os = "linux"

    [[Dynare_preprocessor.download]]
    sha256 = "5259cacb6d3cc839b418ff8c84d7fc141d39a6ac65bfcefeb78c6af0de38452c"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-1+0/Dynare_preprocessor.v4.8.0-1.x86_64-linux-gnu.tar.gz"
[[Dynare_preprocessor]]
arch = "x86_64"
git-tree-sha1 = "da03a074dc4614e7f142c09b95fbce664c3a8553"
os = "windows"

    [[Dynare_preprocessor.download]]
    sha256 = "1d3329d5d08d4b1283095d1cd2297879bf4cfef201d6a3909765a8cf9e5ec620"
    url = "https://github.com/MichelJuillard/Dynare_preprocessor_jll.jl/releases/download/Dynare_preprocessor-v4.8.0-1+0/Dynare_preprocessor.v4.8.0-1.x86_64-w64-mingw32.tar.gz"
