# Autogenerated wrapper script for Dynare_preprocessor_jll for x86_64-w64-mingw32
export dynare_preprocessor

JLLWrappers.@generate_wrapper_header("Dynare_preprocessor")
JLLWrappers.@declare_executable_product(dynare_preprocessor)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        dynare_preprocessor,
        "bin\\dynare-preprocessor.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
